---
title: "Advent of Code Solutions"
author: "Kevin Kent"
date: "12/2/2020"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Day 1

# Part 1

```{r}
library(here)
library(tidyverse)

data <- read.table(here::here("2020", "Inputs", "day_1.txt"))

diffs <- 2020 - data$V1 

data %>%
  filter(V1 %in%  diffs) %>%
  prod(.)

```

# Part 2

```{r}
expand.grid(data$V1, data$V1) %>%
  filter((Var1 + Var2) %in% diffs) %>%
  select(Var1) %>%
  distinct() %>%
  prod(.)
```


# Day 2

## Part 1

```{r}
library(here)
library(tidyverse)

data <- read.table(here::here("2020", "Inputs", "day_2.txt"), sep = " ", col.names = c("lower_upper", "letter", "string")) %>%
  mutate(letter = str_remove_all(letter, ":")) %>%
  separate(lower_upper, into = c("lower", "upper"), sep = "-") 

data %>%
  mutate(string = str_extract_all(string, letter)) %>%
  mutate(length = map(string, ~ length(.))) %>%
  mutate(valid = case_when(
    as.numeric(length) >= as.numeric(lower) & as.numeric(length) <= as.numeric(upper) ~ TRUE,
    TRUE ~ FALSE
  )) %>%
  summarise(sum(valid))
```

## Part 2

```{r}
data %>%
  mutate(lower = as.numeric(lower),
         upper = as.numeric(upper)) %>%
  mutate(string_first = substr(string, lower, lower), 
         string_second = substr(string, upper, upper)) %>%
  mutate(valid = case_when(
    string_first == letter & string_second ==  letter ~ FALSE,
    string_first == letter | string_second == letter ~ TRUE,
    TRUE ~ FALSE
  )) %>%
  summarise(sum(valid))
```

# Day 3

## Part 1 & 2

```{r}

data <- read_lines(here::here("2020", "Inputs", "day_3.txt")) %>%
  as.data.frame(.) %>%
  rename(pattern = 1) 

get_counts <- function(slope, rows, data) {
  
data %>%
  slice(rows) %>%
  mutate(row = row_number()) %>%
  mutate(position = slope*(row - 1) + 1) %>%
  mutate(adj_position = position %% 31) %>%
  mutate(adj_position = case_when(
    adj_position == 0 ~ 31, 
    TRUE ~ adj_position
  ))  %>%
    mutate(match = str_sub(pattern, adj_position, adj_position)) %>%
  filter(match == "#") %>%
  nrow(.)
 
}

slopes <- c(1, 3, 5, 7, 1)
row_ic <-list(1:nrow(data), 1:nrow(data), 1:nrow(data), 1:nrow(data), seq(1, nrow(data), by  = 2))

prod(map2_int(slopes, row_ic, get_counts, data = data))

```

# Day 4

```{r}
data <- read_file(here::here("2020", "Inputs", "day_4.txt")) %>%
  as.data.frame(.) %>%
  rename(pattern = 1) %>%
  separate_rows(pattern, sep = "\n\n") %>%
  mutate(passport_id = row_number()) %>%
  separate_rows(pattern, sep = " |\n") %>%
  separate(pattern, into = c("key", "value"), sep = ":") %>%
  filter(!key %in% c('', 'cid')) %>% 
  mutate(is_present = !is.na(value)) %>%
  group_by(passport_id) %>%
  mutate(num_valid = sum(is_present)) %>%
  ungroup() %>%
  filter(!is.na(value)) %>%
  pivot_wider(names_from = "key", values_from = "value") %>%
  mutate(hgt_units = str_extract(hgt, "[a-z]{2}"), 
         hgt = str_extract(hgt, "[0-9]+")) %>%
  mutate(hgt = as.numeric(hgt)) %>%
    filter(num_valid == 7) 

# part 1

data %>%
  count()

# part 2

data %>%
  filter(1920 <= byr & byr <= 2002 &
        2010  <=  iyr & iyr <= 2020 &
        2020 <=  eyr & eyr <=  2030 &
          !is.na(hgt_units) &
            ((hgt_units == "in" & hgt >= 59 & hgt <= 76) | 
      (hgt_units == "cm" & hgt >= 150 & hgt <= 193)) & str_detect(hcl, "#(([a-f])|([0-9])){6}") & 
        ecl %in% c("amb", "blu", "brn", "gry", "grn", "hzl", "oth")  & 
        str_detect(pid, "^[0-9]{9}$")) %>%
  count()
```

# Day 5

```{r}


data <- read_lines(here::here("2020", "Inputs", "day_5.txt"))

num_cols <- 8
num_rows <- 128
row_sequence <- 0:(num_rows-1)
col_sequence <- 0:(num_cols-1)

halve_seq <- function(seat_sequence, string) {
  
  curr_indication <- substr(string, 1, 1)
  string <- substr(string, 2, nchar(string))
  
  if ((curr_indication == 'F') | (curr_indication == 'L')) {
    
    seat_sequence <- seat_sequence[1:(length(seat_sequence)/2)]
    
  } 
  
  else {
    
    seat_sequence <- seat_sequence[((length(seat_sequence)/2) + 1):length(seat_sequence)]
    
  }
  
  if (length(seat_sequence) == 1) {
    
    seat_sequence
    
  }
  
  else {
    
    halve_seq(seat_sequence, string)
    
  }
  
}

get_id <- function(row, col) {
  
  (row * 8) + col
  
}

 rows <- map_int(data, ~ halve_seq(row_sequence, .))
 cols <- map_int(data, ~ halve_seq(col_sequence, substr(., 8, 10)))
 ids  <- map2_dbl(rows, cols, ~ get_id(.x, .y))
 
 max(ids)
 
 which(!seq(0:858)  %in% ids)

 

```

# Day 6 

```{r}

data <- read_file(here::here("2020", "Inputs", "day_6.txt")) %>%
  as.tibble(.) %>%
  separate_rows(value, sep = "\n\n") %>%
  mutate(group = row_number()) %>%
  separate_rows(value, sep = "\n") %>%
  group_by(group) %>%
  mutate(person = row_number()) %>%
  mutate(value = str_trim(value)) %>%
  ungroup()

# Part 1

data %>%
  separate_rows(value, sep = "")   %>%
  filter(value!='') %>%
  distinct(value, group) %>%
  count(group) %>%
  summarise(sum(n))

# Part 2

data %>%
  group_by(group) %>%
  mutate(num_people = n()) %>%
  separate_rows(value, sep = "")   %>%
  filter(value!='') %>%
  group_by(group, num_people, value) %>%
  summarise(letter_counts = n()) %>%
  ungroup() %>%
  filter(letter_counts == num_people) %>%
  distinct(group, value) %>%
  count(group) %>%
  summarise(sum(n))
  
  

```

# Day 7 

```{r}
data <- read_lines(here::here("2020", "Inputs", "day_7.txt"))  %>%
  tibble(text = .) %>%
  separate(text, into = c("type", "contains"), sep = "contain") %>%
  mutate(contains = str_remove_all(contains, "bags|bag"),
         type = str_trim(str_remove_all(type, "bags|bag")))

find_parents <- function(data, start_bag) {
  
  matches <- which(str_detect(data$contains, start_bag))
  
  if (length(matches) > 0) {
    
    names(matches) <- matches
    
    all <- map(matches, ~ find_parents(data, data$type[.]))
    
  }
  
all
 
}

parents <- find_parents(data, "shiny gold")

parent_names <- names(unlist(parents)) 

length(unique(unlist(str_split(parent_names, "\\."))))

children_data <- data %>%
  rename(parent = 1, child = 2) %>%
  separate_rows(child, sep = ",") %>%
  mutate(num_bags = as.numeric(str_extract(child, "[0-9]{1}"))) %>%
  mutate(child = str_trim(str_remove_all(child, "[0-9]|\\."))) %>%
  drop_na(ch)

children <- children_data$child

names(children) <- children_data$parent

parent_child <- children_data %>%
group_by(parent) %>%
  summarise(child = list(child), counts = list(num_bags))

children  <- parent_child$child
counts  <- parent_child$counts

names(children) <- parent_child$parent
names(counts) <- parent_child$parent

child_bag_counts <- function(children, counts, string = "shiny gold", total = 0) {
  
  if (!string %in% names(counts)) {
    
    total
    
  }
  
    else  {
        
      total <- total + prod(as.numeric(unlist((counts[string]))))*length(counts[string])
      
      
      
      map(children[string], ~ function(result) if (is.null(.)) {
        
        total
      } 
      
      else {
        
        child_bag_counts(children, counts, string = ., total = total)
      })
        
        
        
              
    }
  
}
  
  
test <- child_bag_counts(children, counts)

child_bag_counts(children_data)

```

# Day 8

```{r}
library(here)
library(tidyverse)

data <- read_lines(here::here("2020", "Inputs", "day_8.txt"))

find_infinite <- function(data, accum = 0, location = 1, visited = c()) {
  reached_end <- FALSE
  while (length(visited) == (length(unique((visited))))) {
    start_location <- location
    command <- str_extract(data[location], "^[a-z]{3}")
    num <- str_extract(data[location], "(\\+|-)[0-9]+")
    
    if (command == "jmp") {
    
      num <- parse(text=paste0(location, num))
      location <- eval(num)
    }
    
    if (command == "acc") {
      
      num <- parse(text=paste0(accum, num))
      accum <- eval(num)
      location <- location + 1
    }
    
    if (command == 'nop') {

      location <- location + 1
      
    }
    
      visited <- c(visited, location)
    
       if (start_location == (length(data))) {
     print("reached end")
         reached_end <- TRUE
     
     break
   }
     
    
  }

   list(accum, visited, reached_end)
   

  
}


# part 1

result_1 <- find_infinite(data)

result_1_names <- data[result_1[[2]]]
  

```

```{r}

jmp_to_nop <- function(string) {
  
  str_replace(string, "jmp", "nop")
  
}

nop_to_jmp <- function(string) {
  
  str_replace(string, "nop", "jmp")
  
}

i = 1
found <- FALSE 
all_jmps <- which(str_detect(result_1_names, "jmp"))
all_nops <- which(str_detect(result_1_names, "nop"))

while (found == FALSE & i <= length(all_nops)) {
  data_mod <- data
  data_mod[all_nops[i]] <- nop_to_jmp(data_mod[all_nops[i]])
  result <- find_infinite(data_mod)
  found <- result[[3]]
  i= i + 1
}

i = 1

while (found == FALSE & i <= length(all_jmps)) {
  data_mod <- data
  data_mod[all_jmps[i]] <- jmp_to_nop(data_mod[all_jmps[[i]]])
  result <- find_infinite(data_mod)
  found <- result[[3]]
  i= i + 1
}
```

# Day 9 

```{r}
library(here)
library(tidyverse)

data <- as.numeric(read_lines(here::here("2020", "Inputs", "day_9.txt"))) 

get_begin <- function(curr, diff) {
  
  num <- curr - diff 
  
  if (num <= 0) {
    
    1
  }
  
  else num 
  
}

get_cohort <- function(df, curr) {
  
  df[get_begin(curr, 25):(curr-1)]
  
}

cohorts <- map(seq(26, length(data), by = 1), ~ get_cohort(data, .))

not_found= TRUE
i = 0

while (not_found) {
  
  i = i + 1
  
  combos <- expand.grid(cohorts[[i]], cohorts[[i]]) %>%
    mutate(sums = Var1 + Var2)
    
  not_found <- data[i+25] %in% combos$sums
  

    
}

# Part 1 

answer <- data[25+i]

# Part 2

remaining_data <- data[1:(i+25-1)]

data_df <- tibble(data = data)

not_found = TRUE

lag_additions <- function(data, lag) {
  
  start <- length(data) - lag
  
  sum(data[start:length(data)])
  
}

data_loop <- data

not_found <- TRUE

lag <- 1

## check and expand sequence until either 1) equal to answer or (break) 2) greater than answer (remove last element, repeat  from lag 1)

while (not_found)  {
  
  total <- lag_additions(data_loop, lag)

  if (total ==  answer) {
  
      start <- length(data_loop) - lag
      end <- length(data_loop)
      segment <- data_loop[start:end]
      final_total <- sum(c(min(segment), max(segment)))
      not_found <- FALSE
  
  }
  if (total > answer) {
    
    data_loop <- data_loop[1:(length(data_loop)-1)]
    lag <- 1
    
  }
  
  lag <- lag + 1

  
}

```

## Day 10

### Part 1

```{r}

pad_vct <- function(data_vct) {
  
  
  data_vct <- sort(as.numeric(data_vct))
  
  tibble(data =c(0, data_vct, data_vct[length(data_vct)] +3))
  
}

data_raw <- pad_vct(read_lines(here::here("2020", "Inputs", "day_10.txt")))

data <- data_raw %>%
  mutate(data_lag = lag(data)) %>%
  mutate(diff = data - data_lag)
 
data %>%
  count(diff) 

  prod(result$n, na.rm = TRUE)


```

 
### Part 2

```{r}

library(igraph)
library(here)
library(tidyverse)

options("scipen" = 30)

data_raw <- pad_vct(read_lines(here::here("2020", "Inputs", "day_10_test2.txt")))

possible_pairs_raw <- expand.grid(data_raw$data, data_raw$data) %>%
  mutate(abs_diff = Var2 - Var1) %>%
  filter((abs_diff %in% c(1,2, 3))) %>%
  rename(from = Var1, to = Var2) %>%
  arrange(from) 

possible_pairs_t <- expand.grid(data_raw$data, data_raw$data) %>%
  mutate(abs_diff = Var2 - Var1) %>%
  filter((abs_diff %in% c(1,2, 3))) %>%
    rename(from = Var1, to = Var2) %>%
  select(-abs_diff) %>%
  mutate(present = 1) %>%
  pivot_wider(names_from = from, values_from = present, values_fill = 0) %>%
  select(-to)

answer <- possible_pairs_raw %>%
  count(from) %>%
  rename(times = n) %>%
  count(times) %>%
  mutate(tot = times^n) %>%
  summarise(sum(tot))

testt <- vertex_counts %>%
  mutate(idx = row_number()) 

  2*prod(vertex_counts$n[2:nrow(vertex_counts)])
  mutate(many_more = case_when(
    (idx > 1) ~ (n - 1),
    TRUE ~ n
  )) %>%
  View()

prod(vertex_counts$n)

pairs_list <- possible_pairs_raw$to

names(pairs_list) <- possible_pairs_raw$from


```

```{r}

go_next <- function(key, pairs_list) {
  
  if (min(pairs_list[key]) == 197) {
    
    1
    
  }
  
  else {
    
        possibilities <- pairs_list[key]
    
    
    if (length(possibilities) > 0){
      
      map(possibilities, ~ as.character(.), pairs_list)
      
    }
        
        else {
          
          0
          
        }
  
    
  }
  
}



find_path <- function(location, df) {
  
  if (location == 116) {
    
    1
  }
  
  else {
    
    value <- df$to[location]
    
    matches <- which(df$from[(location+1):nrow(df)] == value)
    
    if (length(matches) > 0) {
      
      map(matches, find_path(location, df))
      
    }
    
    else {
      
      0
      
    }
    
    
    
  }

}

possible_pairs <- possible_pairs_raw

count <- 0

```

## Day 11

```{r}

data_raw <-  read_file(here::here("2020", "Inputs", "day_11.txt"))

data_raw_split <- str_remove_all(data_raw, "\n") %>%
  str_replace_all(., "L", "0") %>%
  str_replace_all(., "#", "1") %>%
  str_split(., "")

get_col <- function(seat, ncol) {
  
  mod  <- seat%%ncol
  
  if (mod == 0) {
    ncol}
  
  else {
    mod
    }
}

checks <- function(seat, layout, ncol) {
  
  curr_col <- get_col(seat, ncol)
  
  idx <- c(seat + 1, seat + ncol + 1, seat - ncol + 1, seat - 1, seat - ncol - 1, seat + ncol - 1, seat + ncol, seat - ncol)
  
  if (curr_col %in%  c(1, ncol)){
    
    if (curr_col == 1) idx <- idx[c(1, 2, 3, 7, 8)]
    if (curr_col == ncol) idx <- idx[c(4, 5, 6, 7, 8)]
      
}
  
  idx <- idx[which(idx %in% 1:(length(layout)))]
  
  layout[idx]
  
}

change_status <- function(seat_num, layout, num_col) {
  
  if ((layout[[seat_num]] == "0") & all(checks(seat_num, layout, num_col) != "1")) {return("1")}
  
  if ((layout[[seat_num]] == "1") & (sum(checks(seat_num, layout, num_col) == "1") >= 4))  {return("0")}
 
  else {return(layout[[seat_num]])}
  
  }

prev <- data_raw_split[[1]]
curr <- data_raw_split[[1]]

should_stop = FALSE

while (!should_stop) {
  
  curr <- map_chr(1:length(prev), ~ change_status(., prev, 90))
  
  should_stop <- all(curr == prev)

  prev <- curr
  
}

sum(prev == "1")

```

```{r}

row_pos <- 10
col_pos <- 9

mtcars[row_pos, col_pos]

nrow_mtcars <- nrow(mtcars)
ncol_mtcars <- ncol(mtcars)

avail_rows_up <- function(row) seq(1,(row-1))
avail_rows_down <- function(row, total_rows) seq(row+1, total_rows)
avail_cols_right <- function(col, total_cols) seq(col + 1, total_cols)
avail_cols_left <- function(col) seq(1, col-1)

left_diag_up <- function(row, col) (row - diff)*(col - diff)
left_diag_down <- function(row, col) (row - diff)*(col - diff)

```

# Day 12

## Part 1

```{r}

library(tidyverse)

data <- tibble(directions =read_lines(here::here("2020", "Inputs", "day_12.txt"))) %>%
   mutate(step = row_number()) %>%
  mutate(command = str_extract(directions, "^[A-Z]"),
         units = as.numeric(str_extract(directions, "[0-9]+"))) %>%
  mutate(units = case_when(
    command == 'L'~ -1*units,
    TRUE ~ units
  )) %>%
  mutate(deg = case_when(
    command %in% c("L", "R") ~ units,
    TRUE ~ 0
  )) %>%
  mutate(deg = case_when(
    step == 1 ~ 0, 
    TRUE ~ deg
  )) %>%
  mutate(position = case_when(
    command %in% c("N", "S", "E", "W") ~ units,
    TRUE ~ NA_real_
  )) %>%
  mutate(cummul_dir = cumsum(deg)) %>%
  mutate(cummul_dir = cummul_dir %% 360)

data %>% 
  mutate(cummul_dir = case_when(
    cummul_dir == 0 ~ "E",
    cummul_dir == 90 ~ "S",
    cummul_dir == 180 ~ "W",
    cummul_dir == 270 ~ "N"
  )) %>%
  filter(!command %in% c("R", "L")) %>%
  mutate(command = case_when(
    command == "F" ~ cummul_dir,
    TRUE ~ command
  )) %>%
  group_by(command) %>%
  summarise(total_moves = sum(units)) %>%
  pivot_wider(names_from = "command", values_from = "total_moves") %>%
  summarise(ans = abs((E-W)) + abs((S - N)))

```

## Part 2

```{r}
part2_clean <- data %>%
    filter(!command %in% c("R", "L")) %>%
  mutate(way_1 = case_when(
    step == 1 ~ 10,
    TRUE ~ 0),
    way_2 = case_when(
      step == 1 ~ 1,
    TRUE ~ 0
    )) %>%
  mutate(way_deg_1 = cummul_dir,
         way_deg_2 = (cummul_dir  + 270) %% 360) %>%
mutate(way_deg_1 = case_when(
    way_deg_1 == 0 ~ "E",
    way_deg_1 == 90 ~ "S",
    way_deg_1 == 180 ~ "W",
    way_deg_1 == 270 ~ "N"
  ),
  way_deg_2 = case_when(
    way_deg_2 == 0 ~ "E",
    way_deg_2 == 90 ~ "S",
    way_deg_2 == 180 ~ "W",
    way_deg_2 == 270 ~ "N"
  )) %>%
  mutate(command_opp = case_when(
    command == "E" ~ "W",
    command == "W" ~ "E",
    command == "N" ~ "S",
    command == "S" ~ "N"
  )) %>%
  mutate(way_1 = case_when(
    way_deg_1 == command ~ way_1 + units,
    way_deg_1 == command_opp ~ way_1 - units,
    TRUE ~ way_1
  ),
  way_2 = case_when(
         way_deg_2 == command ~ way_2 + units,
    way_deg_2 == command_opp ~ way_2 - units,
    TRUE ~ way_2)) %>% 
  mutate(way_1 = cumsum(way_1)) %>%
  mutate(way_2 = cumsum(way_2)) %>%
    mutate(way_deg_1 = case_when(
      way_1 < 0 & way_deg_1 == 'N' ~ 'S',
            way_1 < 0 & way_deg_1 == 'S' ~ 'N',
            way_1 < 0 & way_deg_1 == 'E' ~ 'W',
            way_1 < 0 & way_deg_1 == 'W' ~ 'E',
      TRUE ~ way_deg_1
    ),
        way_deg_2 = case_when(
      way_2 < 0 & way_deg_2 == 'N' ~ 'S',
            way_2 < 0 & way_deg_2 == 'S' ~ 'N',
            way_2 < 0 & way_deg_2 == 'E' ~ 'W',
            way_2 < 0 & way_deg_2 == 'W' ~ 'E',
      TRUE ~ way_deg_2
    )) %>%
  mutate(way_1 = abs(way_1),
         way_2 = abs(way_2))


```
    
```{r}
part2_res <- part2_clean %>%
  filter(command == 'F') %>%
  select(-step, -deg, -position, -command_opp) %>%
 mutate(way_1 = units*way_1,
        way_2 = units*way_2) %>%
  select(way_1, way_2, way_deg_1, way_deg_2) 

bind_rows(part2_res[,c(2,4)], part2_res[,c(1, 3)]) %>%
  rename(move = way_1, dir = way_deg_1) %>%
  mutate(dir = case_when(
    is.na(dir) ~ way_deg_2,
    TRUE ~ dir
  ),
  move = case_when(
    is.na(move) ~ way_2,
    TRUE ~ move
  )) %>%
  select(dir, move) %>%
  group_by(dir) %>%
  summarise(moves = sum(move)) %>%
  pivot_wider(names_from = "dir", values_from = "moves") %>%
  summarise(ans = abs((E-W)) + abs((S - N)))

```

# Day 13

## Part 1

```{python}

d13 = open("Inputs/day_13.txt").read().split("\n")

departure = int(d13[0])

buses = [int(bus) for bus in d13[1].split(",") if bus != 'x']

remainders = [departure % bus for bus in buses]

wait_time = [bus - remainder for bus, remainder in zip(buses, remainders)]

min_wait = min(wait_time)

buses_choose = buses[wait_time.index(min(wait_time))]

buses_choose*min_wait
```

## Part 2

```{python}

bus_ids_all = [bus for bus in d13[1].split(",")]

min_diff = [(int(id),min) for (min, id) in enumerate(bus_ids_all) if id != 'x']

min_diff

def prime_factors(n):
    i = 2
    factors = []
    while i * i <= n:
        if n % i:
            i += 1
        else:
            n //= i
            factors.append(i)
    if n > 1:
        factors.append(n)
    return factors
    

prime_facts = [(prime_factors(num[0]), prime_factors(num[1])) for num in min_diff] 

found = False

i = 0

while not found:
  i+=1
  num = 19*i
  found = (num % 37 == (13)) & (num % 523 == (19))  & (num % 13 == 37)

num
```

```{r}
options("scipen" = 20)
19*(5^2)*(2^2)*271*199*13*7*3*101*11
```

# Day 15

# Part 1

What is the 2020th number spoken?

```{r}

library(purrr)

starting <- c(1,0,18,10,19,6)

possible_nums <- rep(c(0), 30000000)

update_info <- function(num, num_list, position) {
  
  num_list[num + 1] <- position
  
  num_list
  
}

for (i in 1:(length(starting))) {
  
    possible_nums <- update_info(starting[i], possible_nums, i)
  
}

last_num <- starting[length(starting)]

last_num_match_pos <- 0


for (i in (length(starting)+1):30000000) {
  
  if (last_num_match_pos == 0) {
    
    last_num <- 0
    
    last_num_match_pos <- possible_nums[1]
    
    possible_nums[1] <- i
    
  }
  
  else {
    
    last_num <- (i-1) - last_num_match_pos
    
    last_num_match_pos <- possible_nums[last_num+1]
    
    possible_nums[last_num+1] <- i
    
    
  
  }
  
}

last_num






```



